import {FaceDetector,FilesetResolver} from 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/vision_bundle.mjs';
const MODEL='https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite';
const WASM='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm';
const $=s=>document.querySelector(s); const setup=$('#setup'),monitor=$('#monitor'),video=$('#video'),start=$('#start'),cal=$('#calibrate'),recal=$('#recalibrate'),stop=$('#stop'),status=$('#status'),state=$('#state'),debug=$('#debug'),slider=$('#threshold'),tv=$('#thresholdValue');
let detector,stream,ctx,alarmTimer,running=false,lastTime=-1,lastDetect=0,currentWidth=null,safe=Number(localStorage.safeFaceWidth)||null;
slider.oninput=()=>tv.textContent=slider.value+'%';
async function init(){status.textContent='Loading face detector…';const v=await FilesetResolver.forVisionTasks(WASM);detector=await FaceDetector.createFromOptions(v,{baseOptions:{modelAssetPath:MODEL,delegate:'CPU'},runningMode:'VIDEO',minDetectionConfidence:.5,minSuppressionThreshold:.3});}
async function begin(){stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'user'},width:{ideal:640,max:960},height:{ideal:480,max:720},frameRate:{ideal:15,max:20}},audio:false});video.srcObject=stream;await video.play();ctx=new (window.AudioContext||window.webkitAudioContext)();await ctx.resume();monitor.hidden=false;setup.hidden=true;cal.disabled=false;running=true;requestAnimationFrame(loop)}
function largest(ds){return ds?.length?ds.reduce((a,b)=>b.boundingBox.width*b.boundingBox.height>a.boundingBox.width*a.boundingBox.height?b:a):null}
function alarm(on){monitor.classList.toggle('alarm',on);if(on){state.textContent='🚨 TOO CLOSE 🚨';if(!alarmTimer){const beep=()=>{const n=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type='square';o.frequency.setValueAtTime(880,n);o.frequency.setValueAtTime(660,n+.11);o.frequency.setValueAtTime(880,n+.22);g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(.32,n+.015);g.gain.exponentialRampToValueAtTime(.0001,n+.28);o.connect(g);g.connect(ctx.destination);o.start(n);o.stop(n+.3)};beep();alarmTimer=setInterval(beep,420)}}else{state.textContent=safe?'SAFE':'CALIBRATE';if(alarmTimer){clearInterval(alarmTimer);alarmTimer=null}if(navigator.vibrate)navigator.vibrate(0)}}
function calibrate(){if(currentWidth==null){state.textContent='NO FACE';return}safe=currentWidth;localStorage.safeFaceWidth=safe;alarm(false);debug.textContent=`Safe face width: ${(safe*100).toFixed(1)}%`}
function loop(t){if(!running)return;if(video.readyState>=2&&video.currentTime!==lastTime&&t-lastDetect>=120){lastTime=video.currentTime;lastDetect=t;const r=detector.detectForVideo(video,t),f=largest(r.detections);if(f){currentWidth=f.boundingBox.width/video.videoWidth;debug.textContent=`Face ${(currentWidth*100).toFixed(1)}% wide`;if(safe!=null)alarm(currentWidth>=safe*(Number(slider.value)/100));else alarm(false)}else{currentWidth=null;state.textContent=safe?'NO FACE':'CALIBRATE';debug.textContent='No face detected';alarm(false)}}requestAnimationFrame(loop)}
start.onclick=async()=>{start.disabled=true;try{await init();await begin()}catch(e){status.textContent='Could not start: '+e.message;start.disabled=false}};cal.onclick=calibrate;recal.onclick=calibrate;stop.onclick=()=>{running=false;alarm(false);stream?.getTracks().forEach(t=>t.stop());video.srcObject=null;monitor.hidden=true;setup.hidden=false;cal.disabled=true;status.textContent='Camera stopped.'};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
